// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ0VL6gLpYHnDueyDEdCgrA-Z9eEikNHw',
    appId: '1:614912381441:web:cad3d2a7134452f41ca600',
    messagingSenderId: '614912381441',
    projectId: 'softbank-d5d1b',
    authDomain: 'softbank-d5d1b.firebaseapp.com',
    storageBucket: 'softbank-d5d1b.firebasestorage.app',
    measurementId: 'G-8FG1EJ21PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk4Dck92G18YUDWnkEjZBxU8NswSikUFo',
    appId: '1:614912381441:android:3899c4989e9433901ca600',
    messagingSenderId: '614912381441',
    projectId: 'softbank-d5d1b',
    storageBucket: 'softbank-d5d1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvVjFIFjPbpbOGxtS6M_JQbZHF-zFLvjA',
    appId: '1:614912381441:ios:dd251a7debb7539d1ca600',
    messagingSenderId: '614912381441',
    projectId: 'softbank-d5d1b',
    storageBucket: 'softbank-d5d1b.firebasestorage.app',
    iosClientId: '614912381441-si0f13esg8jhr5bg2gtonvo5r4pco0ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokerAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvVjFIFjPbpbOGxtS6M_JQbZHF-zFLvjA',
    appId: '1:614912381441:ios:dd251a7debb7539d1ca600',
    messagingSenderId: '614912381441',
    projectId: 'softbank-d5d1b',
    storageBucket: 'softbank-d5d1b.firebasestorage.app',
    iosClientId: '614912381441-si0f13esg8jhr5bg2gtonvo5r4pco0ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokerAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ0VL6gLpYHnDueyDEdCgrA-Z9eEikNHw',
    appId: '1:614912381441:web:b030d06ee05868bd1ca600',
    messagingSenderId: '614912381441',
    projectId: 'softbank-d5d1b',
    authDomain: 'softbank-d5d1b.firebaseapp.com',
    storageBucket: 'softbank-d5d1b.firebasestorage.app',
    measurementId: 'G-KVLV0SWYQC',
  );

}